backend:
  name: github
  repo: Przemmoo/hossadyna
  branch: main
  base_url: https://hossadyna.pl
  auth_endpoint: /api/auth

media_folder: 'public/images'
public_folder: '/images'

# Site configuration
site_url: https://hossadyna.pl
display_url: https://hossadyna.pl
logo_url: '/images/logo.svg'

collections:
  - name: 'articles'
    label: 'Artykuły'
    folder: 'src/content/articles'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Tytuł', name: 'title', widget: 'string' }
      - { label: 'Data publikacji', name: 'date', widget: 'datetime' }
      - { label: 'Opis', name: 'description', widget: 'text' }
      - { label: 'Obraz', name: 'image', widget: 'image' }
      - { label: 'Zawartość', name: 'body', widget: 'markdown' }
      - {
          label: 'Kategoria',
          name: 'category',
          widget: 'select',
          options:
            ['terapia', 'zdrowie-psychiczne', 'rozwoj-osobisty', 'relacje'],
        }
      - { label: 'Tagi', name: 'tags', widget: 'list', default: [] }

  - name: 'reviews'
    label: 'Opinie'
    folder: 'src/content/reviews'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Imię', name: 'name', widget: 'string' }
      - {
          label: 'Ocena',
          name: 'rating',
          widget: 'number',
          min: 1,
          max: 5,
          step: 1,
        }
      - { label: 'Terapia', name: 'therapy', widget: 'string', required: false }
      - { label: 'Źródło', name: 'source', widget: 'string', required: false }
      - { label: 'Data', name: 'date', widget: 'datetime' }
      - { label: 'Kolejność', name: 'order', widget: 'number', required: false }
      - { label: 'Treść opinii', name: 'body', widget: 'markdown' }

  - name: 'settings'
    label: 'Ustawienia'
    files:
      - label: 'Sekcja O mnie'
        name: 'about'
        file: 'src/content/settings/about.md'
        fields:
          - { label: 'Tytuł sekcji', name: 'title', widget: 'string' }
          - {
              label: 'Pierwszy akapit wprowadzający (format Markdown)',
              name: 'intro_paragraph_1',
              widget: 'markdown',
              hint: 'Możesz używać składni Markdown: **tekst** dla pogrubienia, *tekst* dla kursywy.',
            }
          - {
              label: 'Drugi akapit wprowadzający (format Markdown)',
              name: 'intro_paragraph_2',
              widget: 'markdown',
              hint: 'Możesz używać składni Markdown: **tekst** dla pogrubienia, *tekst* dla kursywy.',
            }
          - {
              label: 'Tytuł sekcji wykształcenia',
              name: 'qualifications_title',
              widget: 'string',
            }
          - {
              label: 'Lista wykształcenia i kwalifikacji',
              name: 'qualifications',
              widget: 'list',
              field:
                {
                  label: 'Kwalifikacja',
                  name: 'qualification',
                  widget: 'string',
                },
            }
          - {
              label: 'Tytuł sekcji podejścia',
              name: 'approach_title',
              widget: 'string',
            }
          - {
              label: 'Opis podejścia terapeutycznego (format Markdown)',
              name: 'approach_description',
              widget: 'markdown',
              hint: 'Możesz używać składni Markdown: **tekst** dla pogrubienia, *tekst* dla kursywy.',
            }
          - {
              label: 'Zdjęcie profilowe',
              name: 'profile_image',
              widget: 'image',
            }
          - {
              label: 'Alt dla zdjęcia profilowego',
              name: 'profile_image_alt',
              widget: 'string',
            }

      - label: 'Informacje kontaktowe'
        name: 'contact'
        file: 'src/content/settings/contact.md'
        fields:
          - { label: 'Telefon', name: 'phone', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
          - { label: 'Adres (footer)', name: 'address', widget: 'text' }
          - {
              label: 'Godziny dostępności telefonu',
              name: 'phone_hours',
              widget: 'text',
            }
          - {
              label: 'Czas trwania sesji',
              name: 'session_duration',
              widget: 'string',
            }
          - { label: 'Formy terapii', name: 'therapy_forms', widget: 'text' }
          - { label: 'Adres gabinetu', name: 'office_address', widget: 'text' }
          - {
              label: 'Facebook',
              name: 'facebook',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Instagram',
              name: 'instagram',
              widget: 'string',
              required: false,
            }
          - {
              label: 'LinkedIn',
              name: 'linkedin',
              widget: 'string',
              required: false,
            }

      - label: 'Widget ZnanyLekarz'
        name: 'znanylekarz'
        file: 'src/content/settings/znanylekarz.md'
        fields:
          - { label: 'Kod widgetu', name: 'widget_code', widget: 'text' }
          - { label: 'Link do profilu', name: 'profile_url', widget: 'string' }
          - {
              label: 'Aktywny',
              name: 'active',
              widget: 'boolean',
              default: true,
            }

      - label: 'SEO'
        name: 'seo'
        file: 'src/content/settings/seo.md'
        fields:
          - { label: 'Tytuł strony', name: 'title', widget: 'string' }
          - { label: 'Opis strony', name: 'description', widget: 'text' }
          - { label: 'Słowa kluczowe', name: 'keywords', widget: 'list' }
          - {
              label: 'Google Analytics ID',
              name: 'ga_id',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Google Tag Manager ID',
              name: 'gtm_id',
              widget: 'string',
              required: false,
            }
